[package]
name = "pecan-compiler"
version = "0.1.0"
authors = ["Jay Lee <BusyJayLee@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "1.0"
quote = "1.0"
proc-macro2 = "1.0"
syn = "1.0"
pecan = { path = "../pecan" }
pecan-types = { path = "../types" }
