[package]
name = "pecan-compiler"
version = "0.1.0"
authors = ["Jay Lee <BusyJayLee@gmail.com>"]
edition = "2018"

[dependencies]
pecan = { path = ".." }
pecan-utils = { path = "../utils" }
pecan-descriptor = { path = "../descriptor" }
id-arena = "2.2"
